# libraries

import os
from snakemake.utils import min_version

min_version("6.4.1")


wildcard_constraints:
    sample="[a-zA-Z\d]+",
    native="[a-zA-Z\d]+",
    control="[a-zA-Z\d]+",




##### setup report #####
configfile: "config/config.yaml"

##### setup singularity #####


# this container defines the underlying OS for each job when using the workflow
# with --use-conda --use-singularity
container: "docker://continuumio/miniconda3"

report: "report/workflow.rst"


include: "rules/common.smk"
include: "rules/align.smk"
include: "rules/readsfiltering.smk"
include: "rules/multi2single.smk"
include: "rules/fast5toblow5.smk"
include: "rules/eventalign.smk"
include: "rules/modetect_tombo.smk"
include: "rules/modetect_xpore.smk"
include: "rules/modetect_m6anet.smk"
include: "rules/modetect_nanocompore.smk"
include: "rules/format.smk"
##### target rules #####


rule all:
    input:
        get_final_output()
        # "results/qc/multiqc_report.html",
        # "results/pca.svg",
