# path or URL to sample sheet (TSV format, columns: SampleName, Condition, Directory...)
samples: config/samples.tsv

params:
  minimap2_transcriptome: " -ax map-ont -L --secondary=no -N 10 -p 0 "
  samtools_filtering: " -F0x2324 -q 10 --min-qlen 80 "
  f5c_eventalign_full: "--print-read-names --signal-index --scale-events --min-mapq 0 --min-recalib-events 50 --samples --rna "
  f5c_eventalign_simple: "--signal-index --scale-events --min-recalib-events 50 --min-mapq 0 --rna "
  xpore_dataprep: "genome"
  nanocompore: "--logit --min_ref_length 50 --overwrite --min_coverage 5 "
  baleen_modcall: " --gmm-component-n 1  --sample 100  "
  baleen_postcall: " --proba-threshold 0.9 "
  xpore: ""
  differr: " -f 1  --median-expr-threshold 1  --min-expr-threshold 1 "
  eligos2: "--max_depth 5000000 --min_depth 5 --esb 0 --oddR 1 --pval 1 "
  epinano_dataprep: " "
  epinano: ""


threads:
  minimap2: 12
  slow5tools: 8
  f5c: 32
  nanocompore: 12
  baleen: 60
  nanopolish: 20
  xpore: 40
  sample_reads: 4
  differr: 16
  eligos: 12
  epinano_dataprep: 12
  epinano: 12


reference:
  genome_fasta: genome.fa
  transcriptome_fasta: transcriptome.fa
  transcriptome_gtf: transcriptome.gtf


realign: False
group: False
baleen:
  use_mem: True
  padding: 1
  coverage: 0.8
  gmm_component_n: 2
  dtw_normalization: shape
  sample: 1000

sample: True
sample_size:
  - 100
  - 200
  - 500
test_times: 10


tools:
  tombo_lsc:
    activate: False
  tombo_msc:
    activate: False
  xpore:
    activate: True
  nanocompore:
    activate: True
  m6anet:
    activate: True
  baleen:
    activate: True
  differr:
    activate: True
  drummer:
    activate: True
  eligos:
    activate: True

target_region: ''


