# path or URL to sample sheet (TSV format, columns: SampleName, Condition, Directory...)
samples: config/samples.tsv

params:
  minimap2_transcriptome: " -ax map-ont -L --secondary=no -N 1 "
  minimap2_genome: " -ax splice -u f -k 14 -G 500000 --secondary=no "
  samtools_filtering: " -F0x2324 -q 10 --min-qlen 80 "
  tombo_lsc: " --store-p-value --minimum-test-reads 2 "
  tombo_msc: " --minimum-test-reads 2 --rna "
  tombo_resquiggle: " --num-most-common-errors 5 --overwrite --rna --skip-index "
  f5c_eventalign_nanocompore: "--print-read-names --signal-index --scale-events --min-mapq 0 --min-recalib-events 50 --samples --rna "
  f5c_eventalign_baleen: "--print-read-names --signal-index --scale-events --min-mapq 0 --min-recalib-events 50 --samples --rna "
  f5c_eventalign_xpore: "--signal-index --scale-events --min-recalib-events 50 --min-mapq 0 --rna "
  nanocompore: "--logit --min_ref_length 50 --overwrite --min_coverage 5 "
  baleen: "  --min-mapq 20 --read-number-threshold 20 --padding 3   "
  baleen_bf: ""
  lafite: ""


threads:
  minimap2: 12
  multi_to_single: 24
  tombo: 24
  slow5tools: 8
  f5c: 32
  m6anet: 32
  nanocompore: 12
  baleen: 12
  lafite: 20


reference:
  genome_fasta: data/ref.fasta
  transcriptome_fasta: data/ref.fasta
  transcriptome_gtf: transcriptome.gtf


tools:
  tombo_lsc:
    activate: True
  tombo_msc:
    activate: True
  xpore:
    activate: True
  nanocompore:
    activate: True
  m6anet:
    activate: True
  baleen:
    activate: True

target_region: ''



